#**Regresión logística**

Al igual que la regresión lineal múltiple, la regresión logística es una técnica para comprobar hipótesis y relaciones. Tiene la caracteristica adicional de permitir una variable de respuesta de tipo categórica.


![DiferenciaRegresionLineal](https://miro.medium.com/max/640/0*gKOV65tvGfY8SMem.png)

![image.png]()

##**Base de datos del titanic**

![image.png]()

In [ ]:
import pandas as pd
import statsmodels.api as sm

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/adiacla/bigdata/master/titanic.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
#Verificar nulos
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
df = df.drop('Cabin', axis = 1)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [ ]:
df = df.dropna()
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [ ]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Embarked        object
dtype: object

In [ ]:
df = df.drop('Name', axis = 1)
df = df.drop('Ticket', axis = 1)
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,1,0,3,male,22.0,1,0,7.2500,S
1,2,1,1,female,38.0,1,0,71.2833,C
2,3,1,3,female,26.0,0,0,7.9250,S
3,4,1,1,female,35.0,1,0,53.1000,S
4,5,0,3,male,35.0,0,0,8.0500,S
...,...,...,...,...,...,...,...,...,...
885,886,0,3,female,39.0,0,5,29.1250,Q
886,887,0,2,male,27.0,0,0,13.0000,S
887,888,1,1,female,19.0,0,0,30.0000,S
889,890,1,1,male,26.0,0,0,30.0000,C
890,891,0,3,male,32.0,0,0,7.7500,Q

In [ ]:
df["Sex2"] = 0
df.Sex2.loc[df.Sex=="female"] = 1
df.Sex2.loc[df.Sex=="male"] = 0
df

<ipython-input-12-8d0d7571fd9b>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Sex2.loc[df.Sex=="female"] = 1
<ipython-input-12-8d0d7571fd9b>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Sex2.loc[df.Sex=="male"] = 0

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Sex2
0,1,0,3,male,22.0,1,0,7.2500,S,0
1,2,1,1,female,38.0,1,0,71.2833,C,1
2,3,1,3,female,26.0,0,0,7.9250,S,1
3,4,1,1,female,35.0,1,0,53.1000,S,1
4,5,0,3,male,35.0,0,0,8.0500,S,0
...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,female,39.0,0,5,29.1250,Q,1
886,887,0,2,male,27.0,0,0,13.0000,S,0
887,888,1,1,female,19.0,0,0,30.0000,S,1
889,890,1,1,male,26.0,0,0,30.0000,C,0
890,891,0,3,male,32.0,0,0,7.7500,Q,0

In [ ]:
df = df.drop('Sex', axis = 1)
df

     PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare Embarked  Sex2
0              1         0       3  22.0      1      0   7.2500        S     0
1              2         1       1  38.0      1      0  71.2833        C     1
2              3         1       3  26.0      0      0   7.9250        S     1
3              4         1       1  35.0      1      0  53.1000        S     1
4              5         0       3  35.0      0      0   8.0500        S     0
..           ...       ...     ...   ...    ...    ...      ...      ...   ...
885          886         0       3  39.0      0      5  29.1250        Q     1
886          887         0       2  27.0      0      0  13.0000        S     0
887          888         1       1  19.0      0      0  30.0000        S     1
889          890         1       1  26.0      0      0  30.0000        C     0
890          891         0       3  32.0      0      0   7.7500        Q     0

[712 rows x 9 columns]

In [ ]:
df["EmbarkedC"] = 0
df.EmbarkedC.loc[df.Embarked=="C"] = 1
df.EmbarkedC.loc[df.Embarked!="C"] = 0
df

<ipython-input-14-def598998efa>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.EmbarkedC.loc[df.Embarked=="C"] = 1
<ipython-input-14-def598998efa>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.EmbarkedC.loc[df.Embarked!="C"] = 0

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Embarked,Sex2,EmbarkedC
0,1,0,3,22.0,1,0,7.2500,S,0,0
1,2,1,1,38.0,1,0,71.2833,C,1,1
2,3,1,3,26.0,0,0,7.9250,S,1,0
3,4,1,1,35.0,1,0,53.1000,S,1,0
4,5,0,3,35.0,0,0,8.0500,S,0,0
...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,39.0,0,5,29.1250,Q,1,0
886,887,0,2,27.0,0,0,13.0000,S,0,0
887,888,1,1,19.0,0,0,30.0000,S,1,0
889,890,1,1,26.0,0,0,30.0000,C,0,1
890,891,0,3,32.0,0,0,7.7500,Q,0,0

In [ ]:
df["EmbarkedS"] = 0
df.EmbarkedS.loc[df.Embarked=="S"] = 1
df.EmbarkedS.loc[df.Embarked!="S"] = 0
df["EmbarkedQ"] = 0
df.EmbarkedQ.loc[df.Embarked=="Q"] = 1
df.EmbarkedQ.loc[df.Embarked!="Q"] = 0
df

<ipython-input-15-2fdab0c5144d>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.EmbarkedS.loc[df.Embarked=="S"] = 1
<ipython-input-15-2fdab0c5144d>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.EmbarkedS.loc[df.Embarked!="S"] = 0
<ipython-input-15-2fdab0c5144d>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.EmbarkedQ.loc[df.Embarked=="Q"] = 1
<ipython-input-15-2fdab0c5144d>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.EmbarkedQ.loc[df.Embarked!="Q"] = 0

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Embarked,Sex2,EmbarkedC,EmbarkedS,EmbarkedQ
0,1,0,3,22.0,1,0,7.2500,S,0,0,1,0
1,2,1,1,38.0,1,0,71.2833,C,1,1,0,0
2,3,1,3,26.0,0,0,7.9250,S,1,0,1,0
3,4,1,1,35.0,1,0,53.1000,S,1,0,1,0
4,5,0,3,35.0,0,0,8.0500,S,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,39.0,0,5,29.1250,Q,1,0,0,1
886,887,0,2,27.0,0,0,13.0000,S,0,0,1,0
887,888,1,1,19.0,0,0,30.0000,S,1,0,1,0
889,890,1,1,26.0,0,0,30.0000,C,0,1,0,0
890,891,0,3,32.0,0,0,7.7500,Q,0,0,0,1

In [ ]:
df = df.drop('Embarked', axis = 1)
df

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Sex2,EmbarkedC,EmbarkedS,EmbarkedQ
0,1,0,3,22.0,1,0,7.2500,0,0,1,0
1,2,1,1,38.0,1,0,71.2833,1,1,0,0
2,3,1,3,26.0,0,0,7.9250,1,0,1,0
3,4,1,1,35.0,1,0,53.1000,1,0,1,0
4,5,0,3,35.0,0,0,8.0500,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,39.0,0,5,29.1250,1,0,0,1
886,887,0,2,27.0,0,0,13.0000,0,0,1,0
887,888,1,1,19.0,0,0,30.0000,1,0,1,0
889,890,1,1,26.0,0,0,30.0000,0,1,0,0
890,891,0,3,32.0,0,0,7.7500,0,0,0,1

In [ ]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Age            float64
SibSp            int64
Parch            int64
Fare           float64
Sex2             int64
EmbarkedC        int64
EmbarkedS        int64
EmbarkedQ        int64
dtype: object

In [ ]:
x = df.iloc[:,[2,3,4,5,6,7,8,9,10]]
y = df.Survived
logit_model=sm.Logit(y,x)
result=logit_model.fit()
print(result.summary())

Optimization terminated successfully.
         Current function value: 0.444061
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:               Survived   No. Observations:                  712
Model:                          Logit   Df Residuals:                      703
Method:                           MLE   Df Model:                            8
Date:                Sat, 30 Sep 2023   Pseudo R-squ.:                  0.3419
Time:                        14:03:33   Log-Likelihood:                -316.17
converged:                       True   LL-Null:                       -480.45
Covariance Type:            nonrobust   LLR p-value:                 3.392e-66
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Pclass        -1.1993      0.165     -7.285      0.000      -1.522      -0.877
Age           -0.0433      0.008     -5.266      0.000      -0.059      -0.027
SibSp         -0.3632      0.129     -2.815      0.005      -0.616      -0.110
Parch         -0.0603      0.124     -0.486      0.627      -0.303       0.183
Fare           0.0014      0.003      0.566      0.572      -0.004       0.006
Sex2           2.6385      0.222     11.871      0.000       2.203       3.074
EmbarkedC      2.9989      0.582      5.157      0.000       1.859       4.139
EmbarkedS      2.5977      0.557      4.663      0.000       1.506       3.690
EmbarkedQ      2.1754      0.794      2.739      0.006       0.619       3.732
==============================================================================

In [ ]:
result.prsquared

0.341928837548777

In [ ]:
import itertools
import statsmodels.api as sm
import pandas as pd

# Supongamos que tienes un DataFrame llamado 'df' con las variables independientes en las columnas 2 a 10 y la variable dependiente 'Survived'.
x = df.iloc[:, [2, 3, 4, 5, 6, 7, 8, 9, 10]]
y = df['Survived']

# Crear una lista de todas las combinaciones posibles de variables, desde 1 hasta n variables
variables = list(x.columns)
combinations = []

for i in range(1, len(variables) + 1):
    combinations.extend(itertools.combinations(variables, i))

best_pseudo_r2 = -1  # Inicializar la variable para almacenar el mejor pseudo R^2
best_model = None    # Inicializar la variable para almacenar el mejor modelo
best_features = None  # Inicializar la variable para almacenar las mejores variables

# Iterar a través de las combinaciones y ajustar modelos de regresión logística
for combo in combinations:
    selected_features = list(combo)
    x_subset = x[selected_features]

    logit_model = sm.Logit(y, x_subset)
    result = logit_model.fit()

    pseudo_r2 = result.prsquared  # Obtener el pseudo R^2

    if pseudo_r2 > best_pseudo_r2:
        best_pseudo_r2 = pseudo_r2
        best_model = result
        best_features = selected_features

    # Imprimir las variables y el pseudo R^2 en esta iteración
    print("Variables:", selected_features)
    print("Pseudo R^2:", pseudo_r2)
    print("=" * 30)

# Imprimir el resumen del mejor modelo
print("Mejor modelo seleccionado con variables:", best_features)
print(best_model.summary())
print("Pseudo R^2 del mejor modelo:", best_pseudo_r2)

Optimization terminated successfully.
         Current function value: 0.646769
         Iterations 4
Variables: ['Pclass']
Pseudo R^2: 0.04152891465984576
==============================
Optimization terminated successfully.
         Current function value: 0.671406
         Iterations 4
Variables: ['Age']
Pseudo R^2: 0.005017787511016558
==============================
Optimization terminated successfully.
         Current function value: 0.687447
         Iterations 4
Variables: ['SibSp']
Pseudo R^2: -0.01875442457075649
==============================
Optimization terminated successfully.
         Current function value: 0.693143
         Iterations 3
Variables: ['Parch']
Pseudo R^2: -0.027194930800908956
==============================
Optimization terminated successfully.
         Current function value: 0.686284
         Iterations 4
Variables: ['Fare']
Pseudo R^2: -0.01703071631375752
==============================
Optimization terminated successfully.
         Current function value: 0.644397
         Iterations 5
Variables: ['Sex2']
Pseudo R^2: 0.04504334673300103
==============================
Optimization terminated successfully.
         Current function value: 0.688879
         Iterations 4
Variables: ['EmbarkedC']
Pseudo R^2: -0.020875723441379668
==============================
Optimization terminated successfully.
         Current function value: 0.663482
         Iterations 4
Variables: ['EmbarkedS']
Pseudo R^2: 0.016761073922826553
==============================
Optimization terminated successfully.
         Current function value: 0.689416
         Iterations 5
Variables: ['EmbarkedQ']
Pseudo R^2: -0.021671994569165243
==============================
Optimization terminated successfully.
         Current function value: 0.645426
         Iterations 4
Variables: ['Pclass', 'Age']
Pseudo R^2: 0.04351859279267822
==============================
Optimization terminated successfully.
         Current function value: 0.645782
         Iterations 4
Variables: ['Pclass', 'SibSp']
Pseudo R^2: 0.04299062486129124
==============================
Optimization terminated successfully.
         Current function value: 0.636123
         Iterations 5
Variables: ['Pclass', 'Parch']
Pseudo R^2: 0.0573044825185981
==============================
Optimization terminated successfully.
         Current function value: 0.613061
         Iterations 6
Variables: ['Pclass', 'Fare']
Pseudo R^2: 0.0914815142399199
==============================
Optimization terminated successfully.
         Current function value: 0.477943
         Iterations 6
Variables: ['Pclass', 'Sex2']
Pseudo R^2: 0.2917180409927862
==============================
Optimization terminated successfully.
         Current function value: 0.626534
         Iterations 5
Variables: ['Pclass', 'EmbarkedC']
Pseudo R^2: 0.07151527315510242
==============================
Optimization terminated successfully.
         Current function value: 0.646111
         Iterations 5
Variables: ['Pclass', 'EmbarkedS']
Pseudo R^2: 0.04250297632448041
==============================
Optimization terminated successfully.
         Current function value: 0.646617
         Iterations 5
Variables: ['Pclass', 'EmbarkedQ']
Pseudo R^2: 0.041753354757995464
==============================
Optimization terminated successfully.
         Current function value: 0.670514
         Iterations 4
Variables: ['Age', 'SibSp']
Pseudo R^2: 0.006339374710631063
==============================
Optimization terminated successfully.
         Current function value: 0.668862
         Iterations 4
Variables: ['Age', 'Parch']
Pseudo R^2: 0.008788066609276224
==============================
Optimization terminated successfully.
         Current function value: 0.627290
         Iterations 6
Variables: ['Age', 'Fare']
Pseudo R^2: 0.07039437781495383
==============================
Optimization terminated successfully.
         Current function value: 0.546480
         Iterations 5
Variables: ['Age', 'Sex2']
Pseudo R^2: 0.1901498296007771
==============================
Optimization terminated successfully.
         Current function value: 0.652540
         Iterations 5
Variables: ['Age', 'EmbarkedC']
Pseudo R^2: 0.03297639775755712
==============================
Optimization terminated successfully.
         Current function value: 0.663108
         Iterations 4
Variables: ['Age', 'EmbarkedS']
Pseudo R^2: 0.017314888969599762
==============================
Optimization terminated successfully.
         Current function value: 0.670014
         Iterations 5
Variables: ['Age', 'EmbarkedQ']
Pseudo R^2: 0.007081309140441916
==============================
Optimization terminated successfully.
         Current function value: 0.685564
         Iterations 4
Variables: ['SibSp', 'Parch']
Pseudo R^2: -0.015964205345371907
==============================
Optimization terminated successfully.
         Current function value: 0.671859
         Iterations 5
Variables: ['SibSp', 'Fare']
Pseudo R^2: 0.00434677845724285
==============================
Optimization terminated successfully.
         Current function value: 0.612464
         Iterations 5
Variables: ['SibSp', 'Sex2']
Pseudo R^2: 0.09236615858054453
==============================
Optimization terminated successfully.
         Current function value: 0.681058
         Iterations 4
Variables: ['SibSp', 'EmbarkedC']
Pseudo R^2: -0.009286463177665238
==============================
Optimization terminated successfully.
         Current function value: 0.663481
         Iterations 4
Variables: ['SibSp', 'EmbarkedS']
Pseudo R^2: 0.01676139243745467
==============================
Optimization terminated successfully.
         Current function value: 0.684778
         Iterations 5
Variables: ['SibSp', 'EmbarkedQ']
Pseudo R^2: -0.014799001640577236
==============================
Optimization terminated successfully.
         Current function value: 0.684601
         Iterations 5
Variables: ['Parch', 'Fare']
Pseudo R^2: -0.014536981950487027
==============================
Optimization terminated successfully.
         Current function value: 0.630297
         Iterations 5
Variables: ['Parch', 'Sex2']
Pseudo R^2: 0.06593906978787689
==============================
Optimization terminated successfully.
         Current function value: 0.688670
         Iterations 4
Variables: ['Parch', 'EmbarkedC']
Pseudo R^2: -0.020567024902563347
==============================
Optimization terminated successfully.
         Current function value: 0.657866
         Iterations 4
Variables: ['Parch', 'EmbarkedS']
Pseudo R^2: 0.025083420663062794
==============================
Optimization terminated successfully.
         Current function value: 0.689408
         Iterations 5
Variables: ['Parch', 'EmbarkedQ']
Pseudo R^2: -0.021660067929341054
==============================
Optimization terminated successfully.
         Current function value: 0.644006
         Iterations 5
Variables: ['Fare', 'Sex2']
Pseudo R^2: 0.04562297237504598
==============================
Optimization terminated successfully.
         Current function value: 0.685365
         Iterations 5
Variables: ['Fare', 'EmbarkedC']
Pseudo R^2: -0.01566928838700865
==============================
Optimization terminated successfully.
         Current function value: 0.631837
         Iterations 6
Variables: ['Fare', 'EmbarkedS']
Pseudo R^2: 0.06365611165777729
==============================
Optimization terminated successfully.
         Current function value: 0.681886
         Iterations 5
Variables: ['Fare', 'EmbarkedQ']
Pseudo R^2: -0.01051359159006604
==============================
Optimization terminated successfully.
         Current function value: 0.644342
         Iterations 5
Variables: ['Sex2', 'EmbarkedC']
Pseudo R^2: 0.04512492022966841
==============================
Optimization terminated successfully.
         Current function value: 0.531615
         Iterations 5
Variables: ['Sex2', 'EmbarkedS']
Pseudo R^2: 0.21217867642484578
==============================
Optimization terminated successfully.
         Current function value: 0.635128
         Iterations 5
Variables: ['Sex2', 'EmbarkedQ']
Pseudo R^2: 0.05878016874453895
==============================
Optimization terminated successfully.
         Current function value: 0.659213
         Iterations 4
Variables: ['EmbarkedC', 'EmbarkedS']
Pseudo R^2: 0.023086665973223508
==============================
Optimization terminated successfully.
         Current function value: 0.685148
         Iterations 5
Variables: ['EmbarkedC', 'EmbarkedQ']
Pseudo R^2: -0.015346402518767954
==============================
Optimization terminated successfully.
         Current function value: 0.659751
         Iterations 5
Variables: ['EmbarkedS', 'EmbarkedQ']
Pseudo R^2: 0.022290394845438044
==============================
Optimization terminated successfully.
         Current function value: 0.644205
         Iterations 5
Variables: ['Pclass', 'Age', 'SibSp']
Pseudo R^2: 0.04532772016615094
==============================
Optimization terminated successfully.
         Current function value: 0.634696
         Iterations 5
Variables: ['Pclass', 'Age', 'Parch']
Pseudo R^2: 0.0594204361921048
==============================
Optimization terminated successfully.
         Current function value: 0.608852
         Iterations 6
Variables: ['Pclass', 'Age', 'Fare']
Pseudo R^2: 0.09771846588308253
==============================
Optimization terminated successfully.
         Current function value: 0.477465
         Iterations 6
Variables: ['Pclass', 'Age', 'Sex2']
Pseudo R^2: 0.29242580345014724
==============================
Optimization terminated successfully.
         Current function value: 0.626534
         Iterations 5
Variables: ['Pclass', 'Age', 'EmbarkedC']
Pseudo R^2: 0.07151555607209015
==============================
Optimization terminated successfully.
         Current function value: 0.645249
         Iterations 5
Variables: ['Pclass', 'Age', 'EmbarkedS']
Pseudo R^2: 0.043781126902949774
==============================
Optimization terminated successfully.
         Current function value: 0.645292
         Iterations 5
Variables: ['Pclass', 'Age', 'EmbarkedQ']
Pseudo R^2: 0.043717168128697304
==============================
Optimization terminated successfully.
         Current function value: 0.636036
         Iterations 5
Variables: ['Pclass', 'SibSp', 'Parch']
Pseudo R^2: 0.057433560782295334
==============================
Optimization terminated successfully.
         Current function value: 0.612533
         Iterations 6
Variables: ['Pclass', 'SibSp', 'Fare']
Pseudo R^2: 0.09226359168237186
==============================
Optimization terminated successfully.
         Current function value: 0.476476
         Iterations 6
Variables: ['Pclass', 'SibSp', 'Sex2']
Pseudo R^2: 0.29389178324802556
==============================
Optimization terminated successfully.
         Current function value: 0.625738
         Iterations 5
Variables: ['Pclass', 'SibSp', 'EmbarkedC']
Pseudo R^2: 0.07269424251686463
==============================
Optimization terminated successfully.
         Current function value: 0.645219
         Iterations 5
Variables: ['Pclass', 'SibSp', 'EmbarkedS']
Pseudo R^2: 0.043825056219392255
==============================
Optimization terminated successfully.
         Current function value: 0.645598
         Iterations 5
Variables: ['Pclass', 'SibSp', 'EmbarkedQ']
Pseudo R^2: 0.043263010873580976
==============================
Optimization terminated successfully.
         Current function value: 0.610721
         Iterations 6
Variables: ['Pclass', 'Parch', 'Fare']
Pseudo R^2: 0.09494905927585973
==============================
Optimization terminated successfully.
         Current function value: 0.477764
         Iterations 6
Variables: ['Pclass', 'Parch', 'Sex2']
Pseudo R^2: 0.29198288494875013
==============================
Optimization terminated successfully.
         Current function value: 0.617181
         Iterations 5
Variables: ['Pclass', 'Parch', 'EmbarkedC']
Pseudo R^2: 0.08537516647925614
==============================
Optimization terminated successfully.
         Current function value: 0.635791
         Iterations 5
Variables: ['Pclass', 'Parch', 'EmbarkedS']
Pseudo R^2: 0.057796519231614996
==============================
Optimization terminated successfully.
         Current function value: 0.636019
         Iterations 5
Variables: ['Pclass', 'Parch', 'EmbarkedQ']
Pseudo R^2: 0.05745887144073769
==============================
Optimization terminated successfully.
         Current function value: 0.473473
         Iterations 6
Variables: ['Pclass', 'Fare', 'Sex2']
Pseudo R^2: 0.2983419844090841
==============================
Optimization terminated successfully.
         Current function value: 0.607211
         Iterations 6
Variables: ['Pclass', 'Fare', 'EmbarkedC']
Pseudo R^2: 0.10015099490620305
==============================
Optimization terminated successfully.
         Current function value: 0.612772
         Iterations 6
Variables: ['Pclass', 'Fare', 'EmbarkedS']
Pseudo R^2: 0.0919096133788071
==============================
Optimization terminated successfully.
         Current function value: 0.613006
         Iterations 6
Variables: ['Pclass', 'Fare', 'EmbarkedQ']
Pseudo R^2: 0.09156314165699997
==============================
Optimization terminated successfully.
         Current function value: 0.470845
         Iterations 6
Variables: ['Pclass', 'Sex2', 'EmbarkedC']
Pseudo R^2: 0.3022374739221665
==============================
Optimization terminated successfully.
         Current function value: 0.477932
         Iterations 6
Variables: ['Pclass', 'Sex2', 'EmbarkedS']
Pseudo R^2: 0.2917341817494782
==============================
Optimization terminated successfully.
         Current function value: 0.477160
         Iterations 6
Variables: ['Pclass', 'Sex2', 'EmbarkedQ']
Pseudo R^2: 0.29287801326117036
==============================
Optimization terminated successfully.
         Current function value: 0.609544
         Iterations 5
Variables: ['Pclass', 'EmbarkedC', 'EmbarkedS']
Pseudo R^2: 0.09669339405200561
==============================
Optimization terminated successfully.
         Current function value: 0.626533
         Iterations 5
Variables: ['Pclass', 'EmbarkedC', 'EmbarkedQ']
Pseudo R^2: 0.0715163354629651
==============================
Optimization terminated successfully.
         Current function value: 0.646104
         Iterations 5
Variables: ['Pclass', 'EmbarkedS', 'EmbarkedQ']
Pseudo R^2: 0.04251350698440348
==============================
Optimization terminated successfully.
         Current function value: 0.665234
         Iterations 4
Variables: ['Age', 'SibSp', 'Parch']
Pseudo R^2: 0.01416429882771153
==============================
Optimization terminated successfully.
         Current function value: 0.616566
         Iterations 6
Variables: ['Age', 'SibSp', 'Fare']
Pseudo R^2: 0.08628780373481737
==============================
Optimization terminated successfully.
         Current function value: 0.530131
         Iterations 6
Variables: ['Age', 'SibSp', 'Sex2']
Pseudo R^2: 0.214378681764671
==============================
Optimization terminated successfully.
         Current function value: 0.651207
         Iterations 5
Variables: ['Age', 'SibSp', 'EmbarkedC']
Pseudo R^2: 0.03495186580337417
==============================
Optimization terminated successfully.
         Current function value: 0.663107
         Iterations 4
Variables: ['Age', 'SibSp', 'EmbarkedS']
Pseudo R^2: 0.017316830034807218
==============================
Optimization terminated successfully.
         Current function value: 0.669314
         Iterations 5
Variables: ['Age', 'SibSp', 'EmbarkedQ']
Pseudo R^2: 0.008117845872310125
==============================
Optimization terminated successfully.
         Current function value: 0.626909
         Iterations 6
Variables: ['Age', 'Parch', 'Fare']
Pseudo R^2: 0.07096002121671185
==============================
Optimization terminated successfully.
         Current function value: 0.540568
         Iterations 5
Variables: ['Age', 'Parch', 'Sex2']
Pseudo R^2: 0.1989118240941129
==============================
Optimization terminated successfully.
         Current function value: 0.650637
         Iterations 5
Variables: ['Age', 'Parch', 'EmbarkedC']
Pseudo R^2: 0.035795519916035135
==============================
Optimization terminated successfully.
         Current function value: 0.657398
         Iterations 4
Variables: ['Age', 'Parch', 'EmbarkedS']
Pseudo R^2: 0.0257771458278101
==============================
Optimization terminated successfully.
         Current function value: 0.667349
         Iterations 5
Variables: ['Age', 'Parch', 'EmbarkedQ']
Pseudo R^2: 0.01103038463755679
==============================
Optimization terminated successfully.
         Current function value: 0.529969
         Iterations 6
Variables: ['Age', 'Fare', 'Sex2']
Pseudo R^2: 0.2146181956044595
==============================
Optimization terminated successfully.
         Current function value: 0.621521
         Iterations 6
Variables: ['Age', 'Fare', 'EmbarkedC']
Pseudo R^2: 0.07894380895673869
==============================
Optimization terminated successfully.
         Current function value: 0.619997
         Iterations 6
Variables: ['Age', 'Fare', 'EmbarkedS']
Pseudo R^2: 0.08120305296117203
==============================
Optimization terminated successfully.
         Current function value: 0.626351
         Iterations 6
Variables: ['Age', 'Fare', 'EmbarkedQ']
Pseudo R^2: 0.07178644039341797
==============================
Optimization terminated successfully.
         Current function value: 0.536565
         Iterations 6
Variables: ['Age', 'Sex2', 'EmbarkedC']
Pseudo R^2: 0.20484431911806467
==============================
Optimization terminated successfully.
         Current function value: 0.521843
         Iterations 5
Variables: ['Age', 'Sex2', 'EmbarkedS']
Pseudo R^2: 0.2266605616891162
==============================
Optimization terminated successfully.
         Current function value: 0.541563
         Iterations 6
Variables: ['Age', 'Sex2', 'EmbarkedQ']
Pseudo R^2: 0.19743715507544168
==============================
Optimization terminated successfully.
         Current function value: 0.652293
         Iterations 5
Variables: ['Age', 'EmbarkedC', 'EmbarkedS']
Pseudo R^2: 0.033341904352947815
==============================
Optimization terminated successfully.
         Current function value: 0.651796
         Iterations 5
Variables: ['Age', 'EmbarkedC', 'EmbarkedQ']
Pseudo R^2: 0.03407842857873178
==============================
Optimization terminated successfully.
         Current function value: 0.659743
         Iterations 5
Variables: ['Age', 'EmbarkedS', 'EmbarkedQ']
Pseudo R^2: 0.02230154534712392
==============================
Optimization terminated successfully.
         Current function value: 0.671793
         Iterations 5
Variables: ['SibSp', 'Parch', 'Fare']
Pseudo R^2: 0.004444516572869706
==============================
Optimization terminated successfully.
         Current function value: 0.610057
         Iterations 5
Variables: ['SibSp', 'Parch', 'Sex2']
Pseudo R^2: 0.09593278528202764
==============================
Optimization terminated successfully.
         Current function value: 0.679849
         Iterations 5
Variables: ['SibSp', 'Parch', 'EmbarkedC']
Pseudo R^2: -0.007494687801734123
==============================
Optimization terminated successfully.
         Current function value: 0.656648
         Iterations 4
Variables: ['SibSp', 'Parch', 'EmbarkedS']
Pseudo R^2: 0.026887595744228276
==============================
Optimization terminated successfully.
         Current function value: 0.682806
         Iterations 5
Variables: ['SibSp', 'Parch', 'EmbarkedQ']
Pseudo R^2: -0.01187640635350351
==============================
Optimization terminated successfully.